---
- name: Deploy to Production Environment with Rolling Updates
  hosts: localhost
  connection: local
  serial: 1
  tasks:
    - name: Ensure pip and requests are installed for docker module
      pip:
        name: 
          - requests
          - docker
        state: present
      become: yes

    - name: Login to GHCR via shell command
      shell: echo "{{ lookup('env', 'GITHUB_TOKEN') }}" | docker login ghcr.io -u "{{ lookup('env', 'GITHUB_ACTOR') }}" --password-stdin

    - name: Pull and update production container
      docker_container:
        name: whats-app-prod
        image: ghcr.io/sheharbano404/shehars-whats-x-advanced-whatsapp-messaging-automation:main
        state: started
        recreate: yes
        ports:
          - "5000:5000"

    - name: Post-deployment health check
      uri:
        url: http://localhost:5000
        method: GET
        status_code: [200, 404]
      register: health_check