  name: Semantic Release and Tagging

  on:
    push:
      branches: [ "main" ]

  jobs:
    release:
      runs-on: ubuntu-latest
      permissions:
        contents: write
        packages: write

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Semantic Release Action
          uses: cycjimmy/semantic-release-action@v4
          with:
            extra_plugins: |
              @semantic-release/git
              @semantic-release/github
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}